name: release

on:
  release:
    types: [published]

jobs:
  generate-txt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # 你可以根据需要选择 Python 版本

    - name: generate_rime_all_schema
      run: |
        python program/release/generate_rime_all_schema_zip.py
    
    - name: generate_shouxin_aux.py
      run: |
        python program/release/generate_shouxin_aux.py

    - name: generate_moqi_schema.py
      run: |
        python program/release/generate_moqi_schema.py

    - name: generate_xh_schema.py
      run: |
        python program/release/generate_xh_schema.py

    - name: generate_zrm_schema.py
      run: |
        python program/release/generate_zrm_schema.py

    - name: generate_fancha_en_jp.py
      run: |
        python program/release/generate_fancha_en_jp_schema.py

    - name: Upload rime-all
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        asset_path: rime-所有方案全家桶.zip
        asset_name: rime-所有方案全家桶.zip
        asset_content_type: application/zip
        upload_url: ${{ github.event.release.upload_url }}

    - name: Upload shouxin
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        asset_path: 墨奇码辅助码for手心输入法.txt
        asset_name: 墨奇码辅助码for手心输入法.txt
        asset_content_type: text/plain
        upload_url: ${{ github.event.release.upload_url }}

    - name: Upload rime-moqi
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        asset_path: rime-墨奇音形全家桶(4万字支持小鹤自然码微软搜狗双拼辅).zip
        asset_name: rime-墨奇音形全家桶(4万字支持小鹤自然码微软搜狗双拼辅).zip
        asset_content_type: application/zip
        upload_url: ${{ github.event.release.upload_url }}
    
    - name: Upload rime-xh
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        asset_path: rime-墨奇版小鹤双拼鹤形.zip
        asset_name: rime-墨奇版小鹤双拼鹤形.zip
        asset_content_type: application/zip
        upload_url: ${{ github.event.release.upload_url }}

    - name: Upload rime-zrm
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        asset_path: rime-墨奇版自然码双拼辅助码.zip
        asset_name: rime-墨奇版自然码双拼辅助码.zip
        asset_content_type: application/zip
        upload_url: ${{ github.event.release.upload_url }}

    - name: Upload rime-fancha
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        asset_path: rime-反查-英语-日语等.zip
        asset_name: rime-反查-英语-日语等.zip
        asset_content_type: application/zip
        upload_url: ${{ github.event.release.upload_url }}
